import type { Car } from "./types";

export const mockCars: Car[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2021,
    mileage: 30000,
    condition: "excellent",
    price: 25000,
    description: "A reliable and fuel-efficient sedan, perfect for families and commuters. Well-maintained with all service records available.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "John Doe",
    zipCode: "90210",
  },
  {
    id: 2,
    make: "Honda",
    model: "CR-V",
    year: 2020,
    mileage: 45000,
    condition: "good",
    price: 22000,
    description: "Spacious and versatile SUV with a great safety record. Ideal for road trips and daily driving.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "Jane Smith",
    zipCode: "10001",
  },
  {
    id: 3,
    make: "Ford",
    model: "F-150",
    year: 2019,
    mileage: 60000,
    condition: "good",
    price: 35000,
    description: "The best-selling truck in America for a reason. Powerful V8 engine, tow package included. Ready for work or play.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "Iron Works",
    zipCode: "75201",
  },
  {
    id: 4,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    mileage: 15000,
    condition: "excellent",
    price: 40000,
    description: "Long Range model with Autopilot. Sleek, fast, and fully electric. Skip the gas station forever.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "Tech Enthusiast",
    zipCode: "94107",
  },
  {
    id: 5,
    make: "BMW",
    model: "3 Series",
    year: 2018,
    mileage: 50000,
    condition: "fair",
    price: 18000,
    description: "Experience the ultimate driving machine. Sport package with leather seats. Some cosmetic wear but mechanically sound.",
    imageUrls: ["https://placehold.co/600x400.png"],
    seller: "Driving Dreams",
    zipCode: "33109",
  },
  {
    id: 6,
    make: "Subaru",
    model: "Outback",
    year: 2020,
    mileage: 55000,
    condition: "excellent",
    price: 26000,
    description: "Symmetrical All-Wheel Drive makes this the perfect car for any weather. Top trim level with all features.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "Adventure Awaits",
    zipCode: "80202",
  },
   {
    id: 7,
    make: "Jeep",
    model: "Wrangler",
    year: 2017,
    mileage: 70000,
    condition: "good",
    price: 24000,
    description: "Iconic off-road vehicle. Comes with a soft top and hard top. Ready for your next adventure.",
    imageUrls: ["https://placehold.co/600x400.png"],
    seller: "Off-Road Joe",
    zipCode: "84042",
  },
  {
    id: 8,
    make: "Chevrolet",
    model: "Corvette",
    year: 2023,
    mileage: 5000,
    condition: "excellent",
    price: 85000,
    description: "Mid-engine masterpiece. Z51 Performance Package. An American supercar that turns heads everywhere.",
    imageUrls: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    seller: "Speed Demon",
    zipCode: "42101",
  }
];
